const QKeys = {
  GET_EVENT: 'GET_EVENT',
  GET_EVENTS: 'GET_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  //Month
  BUILD_MONTHS: 'BUILD_MONTHS-V2',
  //Ask
  GET_MODEL_STATUS: 'GET_MODEL_STATUS',
  ASK_MODEL: 'ASK_MODEL',
};

export default QKeys;
